import { chromium } from 'playwright';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:1100},deviceScaleFactor:1});
await page.goto('http://127.0.0.1:5000');
await page.screenshot({path:'artifacts/formulario.png',fullPage:true});
await page.locator('#fecha').fill('2026-09-19');
await page.getByRole('button',{name:'Estimar demanda de la ruta'}).click();
await page.getByText('Estimación calculada').waitFor();
await page.waitForTimeout(1000);
await page.screenshot({path:'artifacts/interfaz.png',fullPage:true});
const bad=await page.request.post('http://127.0.0.1:5000/',{form:{zona:0,fecha:'2026-09-19',promocion:1,demanda_lag7:100}});
await page.setContent(await bad.text());
await page.screenshot({path:'artifacts/error_formulario.png',fullPage:true});
await page.goto('http://127.0.0.1:8000/docs');
await page.getByRole('button',{name:'Enviar solicitud de prueba'}).click();
await page.getByText('HTTP 200').waitFor();
await page.screenshot({path:'artifacts/api_docs.png',fullPage:true});
const response=await page.request.post('http://127.0.0.1:8000/predict',{data:{zona:1,dia_semana:5,mes:12,promocion:1,demanda_lag7:95.0}});
await fs.writeFile('artifacts/ejemplo_api.json',JSON.stringify({request:{zona:1,dia_semana:5,mes:12,promocion:1,demanda_lag7:95.0},status:response.status(),response:await response.json()},null,2));
await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:5000');
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw Error('Desborde móvil');
await page.screenshot({path:'artifacts/interfaz_movil.png',fullPage:true});
await browser.close();
